### PR TITLE
Fix pagination issue in local and global timelines

### PR DESCRIPTION
**Pull request by ghost**
Fix the pagination for the global and locale timelines

### CODE REVIEW

**Comment by ghost** [comment]
I might need to test with these timelines, but they are flagged as experimental.

https://misskey.xyz/docs/en-US/api/endpoints/notes/local-timeline
https://misskey.xyz/docs/en-US/api/endpoints/notes/global-timeline


capture d ecran 2018-12-30 a 17 28 49

capture d ecran 2018-12-30 a 17 31 14


capture d ecran 2018-12-30 a 17 29 05

**Comment by ibrokemypie** [comment]
this works great on local timeline, however global timeline doesnt seem to work/refresh? though perhaps thats a different issue

**Comment by ibrokemypie** [comment]
#42

**Comment by ghost** [comment]
Yes, currently I am fixing pagination, I will check what it is going wrong with pull to refresh

**Pull request merged**
